секция Artstudio
cy4ok/BookingHotel pull request #35
Opened 2020-11-20 11:49 UTC by Xela198001

добавление модального окна при клике на карточку номера

2020-11-20 19:14 UTC, Konfeta3-33 requested changes

2020-11-20 19:14 UTC, Konfeta3-33 commented on client/src/components/ArtStudio/ArtStudio.jsx
> +              <a href="/contacts" className="btn btn-iconText">
Саша, a теперь должна быть в виде <Link to="/ContactsPage" ... />

2020-11-20 19:14 UTC, Konfeta3-33 commented on client/src/components/ArtStudio/Card/Card.jsx
> +                href="/booking?apartment=DLX&amp;hotel-id=1"
Здесь должна быть ссылка на страницу BookingPage через Link

2020-11-20 19:14 UTC, Konfeta3-33 commented on client/src/components/ArtStudio/Cards/Cards.jsx
> +          {cards.map((item,index) => (
index тут не нужен, если ты его не используешь

2020-11-20 19:14 UTC, Konfeta3-33 commented on client/src/components/ArtStudio/Modal/Modal.css
> +  background-color: #fff;
Этот же цвет идет по умолчанию?

2020-11-20 19:14 UTC, Konfeta3-33 commented on client/src/components/ArtStudio/Modal/Modal.jsx
> +                    href="/booking?apartment=DLX&amp;hotel-id=1"
Здесь тоже надо сделать ссылку через Link и переадресацию на страницу BookingPage

2020-11-20 19:14 UTC, Konfeta3-33 commented on client/src/components/ArtStudio/Modal/Modal.css
> +  background-color: #eee;
Этот свой класс можно заменить на border-r и border-gray-300 или 200 и сделать бордер у вышестоящего дива

2020-11-20 19:14 UTC, Konfeta3-33 commented on client/src/components/ArtStudio/Slider/Slider.jsx
> +export default SimpleSlider;
Не забывай про пустые строки в конце - их надо добавлять

2020-11-21 08:48 UTC, cy4ok commented on client/src/components/ArtStudio/ArtStudio.jsx
> +              <a href="/contacts" className="btn btn-iconText">
и class="btn btn-iconText" должно быть className="btn btn-iconText"

2020-11-21 10:22 UTC, Xela198001 commented on client/src/components/ArtStudio/ArtStudio.jsx
> +              <a href="/contacts" className="btn btn-iconText">
исправил

2020-11-21 10:22 UTC, Xela198001 commented on client/src/components/ArtStudio/Card/Card.jsx
> +                href="/booking?apartment=DLX&amp;hotel-id=1"
исправил

2020-11-21 10:22 UTC, Xela198001 commented on client/src/components/ArtStudio/Modal/Modal.css
> +  background-color: #fff;
исправил

2020-11-21 10:22 UTC, Xela198001 commented on client/src/components/ArtStudio/Modal/Modal.jsx
> +                    href="/booking?apartment=DLX&amp;hotel-id=1"
исправил

2020-11-21 10:23 UTC, Xela198001 commented on client/src/components/ArtStudio/Modal/Modal.css
> +  background-color: #eee;
исправил

2020-11-21 10:23 UTC, Xela198001 commented on client/src/components/ArtStudio/Slider/Slider.jsx
> +export default SimpleSlider;
хорошо

2020-11-21 10:43 UTC, Konfeta3-33 requested changes

2020-11-21 10:43 UTC, Konfeta3-33 commented on client/src/components/ArtStudio/Card/Card.jsx
> +              src={require(`./img/${this.state.item.images[0]}`).default}
Лучше не привязываться к индексу массива, а передавать конкретный компонент Img пропсом (item.img), тогда не придётся прописывать require.

2020-11-21 10:43 UTC, Konfeta3-33 commented on client/src/components/ArtStudio/Card/Card.jsx
> +              <span className="block w-full">{this.props.item.title[1]}</span>
Здесь тоже лучше разделить title на два, и не привязываться к индексу; например, mainTitle, secondTitle (или typeOfApartment)

2020-11-21 10:43 UTC, Konfeta3-33 commented on client/src/components/ArtStudio/Cards/Items.js
> +    title: ["ARTSTUDIO Nevsky", "Superior"],
Вот этот title лучше разбить

2020-11-21 10:43 UTC, Konfeta3-33 commented on client/src/components/ArtStudio/Cards/Items.js
> +    images: ["superior.jpg"],
Импорт картинок лучше сделать в этом файле (как я раньше и писала, через import) и передавать уже как компонент ниже по дереву.
Я так понимаю, в карточке есть основная картинка и много других - их тоже лучше разбить на mainImg и images (images сделать массивом и перебирать их там где надо)

2020-11-21 10:43 UTC, Konfeta3-33 commented on client/src/components/ArtStudio/Modal/Modal.jsx
> +                    require(`../Card/img/${this.props.item.images[0]}`).default
Здесь тоже лучше не привязываться к индексу, а сделать по аналогии с Card

2020-11-21 10:43 UTC, Konfeta3-33 commented on client/src/components/ArtStudio/Modal/Modal.jsx
> +                  {`${this.props.item.title[1]} ${this.props.item.area} `}<span className="inline">м<sup>2</sup></span>
Здесь тоже индекс

2020-11-21 10:43 UTC, Konfeta3-33 commented on client/src/components/ArtStudio/Slider/Slider.jsx
> +            <img src={require(`./img/${img}`).default} width="100%" key={index} alt=""/>
Здесь тоже картинки лучше импортировать в списке картинок и передавать сюда уже массив компонентов, чтобы убрать require.

2020-11-21 16:26 UTC, Xela198001 commented on client/src/components/ArtStudio/Modal/Modal.jsx
> +                  {`${this.props.item.title[1]} ${this.props.item.area} `}<span className="inline">м<sup>2</sup></span>
исправил

2020-11-21 16:26 UTC, Xela198001 commented on client/src/components/ArtStudio/Modal/Modal.jsx
> +                    require(`../Card/img/${this.props.item.images[0]}`).default
исправил

2020-11-21 16:27 UTC, Xela198001 commented on client/src/components/ArtStudio/Cards/Items.js
> +    images: ["superior.jpg"],
сделал

2020-11-21 16:27 UTC, Xela198001 commented on client/src/components/ArtStudio/Card/Card.jsx
> +              <span className="block w-full">{this.props.item.title[1]}</span>
разделил

2020-11-21 16:27 UTC, Xela198001 commented on client/src/components/ArtStudio/Card/Card.jsx
> +              src={require(`./img/${this.state.item.images[0]}`).default}
исправил

2020-11-21 22:22 UTC, Konfeta3-33 requested changes
Саша, все хорошо. Небольшие комментарии.

2020-11-21 22:22 UTC, Konfeta3-33 commented on client/src/components/ArtStudio/Card/Card.jsx
> +            <Link
Саша, тут переадресация должна быть на "/booking". Подправь, пожалуйста.

2020-11-21 22:22 UTC, Konfeta3-33 commented on client/src/components/ArtStudio/Modal/Modal.jsx
> +                      to="/bookingpage"
Здесь тоже надо будет подкорректировать на "/booking"

2020-11-21 22:22 UTC, Konfeta3-33 commented on client/src/components/ArtStudio/Slider/Item.js
> +export default ;
Саша, а ты уверен, что этот файл нужен?

2020-11-21 22:22 UTC, Konfeta3-33 commented on client/src/components/ArtStudio/Slider/Items.js
> +export default Items;
Саша, а если сделать просто массив из слайдов? Будет работать? Вот так:
const images = [slide1, slide2, slide3, slide4, slide5...]

2020-11-21 22:39 UTC, Xela198001 commented on client/src/components/ArtStudio/Slider/Item.js
> +export default ;
убрал, заметил после того как запушил

2020-11-21 22:40 UTC, Xela198001 commented on client/src/components/ArtStudio/Slider/Items.js
> +export default Items;
возможно будет работать, поппробую

2020-11-21 22:41 UTC, Konfeta3-33 commented on client/src/components/ArtStudio/Slider/SlideItem.jsx
> +import  Items from './Items';
Items тут не используются, можно удалить.

2020-11-21 22:46 UTC, Xela198001 commented on client/src/components/ArtStudio/Modal/Modal.jsx
> +                      to="/bookingpage"
исправил

2020-11-21 22:46 UTC, Xela198001 commented on client/src/components/ArtStudio/Card/Card.jsx
> +            <Link
исправил

2020-11-21 22:58 UTC, Xela198001 commented on client/src/components/ArtStudio/Slider/SlideItem.jsx
> +import  Items from './Items';
убрал

2020-11-21 23:07 UTC, Xela198001 commented on client/src/components/ArtStudio/Slider/Items.js
> +export default Items;
переделал, не идет, картинки не подгружаются, вернул все обратно

2020-11-23 19:26 UTC, Konfeta3-33 approved these changes

2020-11-23 21:02 UTC, Konfeta3-33 approved these changes

2020-11-23 21:04 UTC, Konfeta3-33 approved these changes
@cy4ok Вася, можно мерджить

2020-11-25 07:45 UTC, merged