Change header and update it in pages
cy4ok/BookingHotel pull request #38
Opened 2020-11-20 19:00 UTC by ElenaDitiateva

2020-11-20 20:43 UTC, Konfeta3-33 requested changes
Лена, несколько комментариев и надо удалить лишние коммиты

2020-11-20 20:43 UTC, Konfeta3-33 commented on client/src/components/Header/Header.jsx
> +    const city = this.props.city;
Лена, а почему у тебя город вынесен в отдельный пропс?

2020-11-20 20:43 UTC, Konfeta3-33 commented on client/src/components/Header/Header.jsx
> +    const maintitle = this.props.maintitle;
Лучше использовать camelCase = smallTitle

2020-11-20 20:43 UTC, Konfeta3-33 commented on client/src/tailwind.css
> +  font-size: 54px;
это класс text-6xl или text-5xl

2020-11-20 20:43 UTC, Konfeta3-33 commented on client/src/tailwind.css
> +  line-height: 56px;
если использовать класс выше, то это тоже можно убрать

2020-11-20 20:43 UTC, Konfeta3-33 commented on client/src/tailwind.css
> +  height: 620px;
все эти # (обертки) мы убираем

2020-11-20 20:43 UTC, Konfeta3-33 commented on client/src/tailwind.css
>  #MainPage header, #ApartmentsPage header, #ToClientsPage header {
Эти # тоже убираем

2020-11-20 20:43 UTC, Konfeta3-33 commented on client/src/pages/ApartmentsPage.js
> +      <Header smalltitle="от 2 800 руб." maintitle="ARTSTUDIO Nevsky" city="ул. 2-ая Советская, 4Б, стр.1"/>
это не city, тут больше подходит address; судя по верстке он будет h1, а должен быть меньше

2020-11-20 20:43 UTC, Konfeta3-33 commented on client/src/pages/ApartmentsPage.js
>      <div id="ApartmentsPage">
все такого рода # убираем

2020-11-20 20:43 UTC, Konfeta3-33 commented on client/src/components/Header/Header.jsx
> +          <h1 className="city mb-20">{city}</h1>
Обрати внимание, что на разных страницах разный размер этого пропса, а на главной странице, например, его вообще нет

2020-11-20 20:43 UTC, Konfeta3-33 commented on client/src/pages/MainPage.js
> +      <Header smalltitle="Дом вдали от дома" maintitle="ARTSTUDIO - апарт-отель в" city="Санкт-Петербурге"/>
Здесь не надо Перебург выносить в отдельный пропс

2020-11-21 10:42 UTC, ElenaDitiateva commented on client/src/components/Header/Header.jsx
> +    const city = this.props.city;
Для переноса на следующую строку

2020-11-21 10:42 UTC, ElenaDitiateva commented on client/src/components/Header/Header.jsx
> +    const maintitle = this.props.maintitle;
+

2020-11-21 10:42 UTC, ElenaDitiateva commented on client/src/tailwind.css
> +  height: 620px;
Я уже удалила HeaderBrown в прошлом коммите

2020-11-21 10:43 UTC, ElenaDitiateva commented on client/src/tailwind.css
>  #MainPage header, #ApartmentsPage header, #ToClientsPage header {
Я при помощи # меняю стили хэдэра

2020-11-21 10:43 UTC, ElenaDitiateva commented on client/src/components/Header/Header.jsx
> +          <h1 className="city mb-20">{city}</h1>
На главной они тоже есть

2020-11-21 10:43 UTC, ElenaDitiateva commented on client/src/pages/MainPage.js
> +      <Header smalltitle="Дом вдали от дома" maintitle="ARTSTUDIO - апарт-отель в" city="Санкт-Петербурге"/>
А по-другому не переносится Санкт-Петербург на другую строку

2020-11-21 10:48 UTC, Konfeta3-33 commented on client/src/components/Header/Header.jsx
> +    const city = this.props.city;
Это лучше сделать с помощью ограничения ширины блока для текста

2020-11-21 10:50 UTC, Konfeta3-33 commented on client/src/components/Header/Header.jsx
> +          <h1 className="city mb-20">{city}</h1>
Есть mainTitle, а city - Санкт-Петербург не должен быть пропсом

2020-11-21 10:51 UTC, Konfeta3-33 commented on client/src/pages/MainPage.js
> +      <Header smalltitle="Дом вдали от дома" maintitle="ARTSTUDIO - апарт-отель в" city="Санкт-Петербурге"/>
Ограничь ширину этого блока

2020-11-21 10:55 UTC, Konfeta3-33 commented on client/src/tailwind.css
> +  height: 620px;
Для упрощения и читаемости кода лучше использовать два хедера (пока, потом может усложним): коричневый и тот, что с картинкой на bg. Картина должна приходить пропсом, также как и title и другие параметры.

2020-11-21 10:58 UTC, Konfeta3-33 commented on client/src/tailwind.css
>  #MainPage header, #ApartmentsPage header, #ToClientsPage header {
Они должны меняться с помощью пропсов.

2020-11-21 11:16 UTC, ElenaDitiateva commented on client/src/tailwind.css
> +  height: 620px;
У меня сейчас по умолчанию стоит коричневый bg, а по id подтягивается картинка. Давай пока оставим так, а позже попытаюсь через пропсы сделать.

2020-11-21 17:28 UTC, ElenaDitiateva commented on client/src/components/Header/Header.jsx
> +    const city = this.props.city;
Ок, сделала)

2020-11-21 21:53 UTC, Konfeta3-33 requested changes

2020-11-21 21:53 UTC, Konfeta3-33 commented on client/src/components/Header/Header.jsx
> +    const camelCase = this.props.camelCase;
Лена, camelCase - это стиль написания переменных, значит что первая буква пишется маленькой, а второе слово в переменной (слитное) с большой буквы (т.е. переменная должна выглядеть примерно так - smallTitle)

2020-11-21 21:53 UTC, Konfeta3-33 commented on client/src/components/Header/Header.jsx
> +    const maintitle = this.props.maintitle;
Аналогично с переменной mainTitle

2020-11-21 21:53 UTC, Konfeta3-33 commented on client/src/components/Header/Header.jsx
> +            <div className="container">
Зачем ты тут повторяешь класс container? Тебе надо все твои дивы обернуть в этот класс и не будет тогда повторений и лишних дивов. И все твои компоненты будут выровнены.

2020-11-23 08:16 UTC, Konfeta3-33 requested changes
Лена, все хорошо, но хранить картинки в public не стоит

2020-11-25 07:51 UTC, Konfeta3-33 approved these changes
Лена, все хорошо

2020-11-25 07:51 UTC, merged