Добавление страницы Офисы в аренду
cy4ok/BookingHotel pull request #41
Opened 2020-11-23 20:42 UTC by svetikfcz

https://trello.com/c/zWUa7MZZ

2020-11-23 21:01 UTC, Konfeta3-33 requested changes
Света, привет! Все хорошо, небольшие комментарии.
P.s. не забывай про пустую строку в конце файлов

2020-11-23 21:01 UTC, Konfeta3-33 commented on client/src/components/Offices/Offices.jsx
> +            </ul> */}
Света, такого рода комментарии лучше удалять из кода

2020-11-23 21:01 UTC, Konfeta3-33 commented on client/src/components/Offices/OfficesListItem.jsx
> +      <li className="clients_sections_list relative pl-6 mt-4">
Света, а что за класс clients_sections_list? Ты его куда-нибудь добавляла?

2020-11-23 21:05 UTC, svetikfcz commented on client/src/components/Offices/Offices.jsx
> +            </ul> */}
дааа, хотела удалить, но забыла

2020-11-23 21:06 UTC, svetikfcz commented on client/src/components/Offices/OfficesListItem.jsx
> +      <li className="clients_sections_list relative pl-6 mt-4">
а вот по этому хотела спросить, тоже про единообразие. Там на странице Clients по сути те же стили, подумала зачем новое писать, если уже есть

2020-11-24 11:02 UTC, Konfeta3-33 approved these changes
@cy4ok Вася, можно мерджить

2020-11-25 07:46 UTC, merged