Infrastructure
cy4ok/BookingHotel pull request #42
Opened 2020-11-25 11:22 UTC by newksyuha

[https://trello.com/c/yojV65B8](url)

2020-11-25 16:43 UTC, Konfeta3-33 requested changes
Оксана, все хорошо. Небольшие комментарии

2020-11-25 16:43 UTC, Konfeta3-33 commented on client/src/components/Infrastructure/style/style.css
> +    background-size: cover;
Оксана, эти св-ва можно прописать с помощью tailwind

2020-11-25 16:43 UTC, Konfeta3-33 commented on client/src/components/Infrastructure/style/style.css
> +    color: rgba(57,57,55,.6);
Этот цвет есть у нас в основных цветах, посмотри файл tailwind.config

2020-11-25 16:43 UTC, Konfeta3-33 commented on client/src/components/Infrastructure/style/style.css
> +    width: 100%;
Это св-во можно прописать как w-full

2020-11-25 16:43 UTC, Konfeta3-33 commented on client/src/components/Infrastructure/style/style.css
> +    background-size: cover;
Эти тоже есть в tailwind

2020-11-25 16:43 UTC, Konfeta3-33 commented on client/src/components/OurAdvantages/OurAdvantagesItem.jsx
> +function OurAdvantagesItem = ({ icon, title, subtitel }) => {
Оксана, в subtitle тоже ошибка :)

2020-11-25 16:59 UTC, newksyuha commented on client/src/components/OurAdvantages/OurAdvantagesItem.jsx
> +function OurAdvantagesItem = ({ icon, title, subtitel }) => {
Увидела уже после отправки. Посмотрю исправлю.

2020-12-02 16:23 UTC, Konfeta3-33 approved these changes

2020-12-02 16:23 UTC, merged