Update ApartmentsPage: added OurAdvantages and Apartments
cy4ok/BookingHotel pull request #51
Opened 2020-11-29 18:46 UTC by ElenaDitiateva

2020-12-02 17:53 UTC, Konfeta3-33 requested changes

2020-12-02 17:53 UTC, Konfeta3-33 commented on client/src/components/ArtStudio/Card/Card.jsx
> +              {`${this.props.item.title}` && `${this.props.item.title}, `}
Очень неочевидно что здесь происходит. Но что точно можно сказать - интерполяция в начале не нужна
```
{this.props.item.title && `${this.props.item.title}, `}
```

2020-12-02 17:53 UTC, Konfeta3-33 commented on client/src/components/Apartments/Cards.jsx
> +export default Cards;
Этот файл надо брать из Артстудио и на главной странице выводить три карточки, а на др. странице полностью все категории

2020-12-02 17:53 UTC, Konfeta3-33 commented on client/src/tailwind.css
> +}
Это все надо подтянуть из main.

2020-12-02 17:53 UTC, Konfeta3-33 commented on client/src/components/OurAdvantages/OurAdvantagesItem.jsx
> +function OurAdvantagesItem({ icon, titel, text }) {
Это тоже исправили уже и надо подтянуть из main.

2020-12-02 17:54 UTC, Konfeta3-33 commented
Лена, надо подтянуть все изменения из main и немного подкорректировать свои компоненты.

2020-12-05 18:55 UTC, ElenaDitiateva commented on client/src/components/ArtStudio/Card/Card.jsx
> +              {`${this.props.item.title}` && `${this.props.item.title}, `}
Интерполяция в начале нужна, иначе код не работает

2020-12-05 19:00 UTC, ElenaDitiateva commented on client/src/components/ArtStudio/Card/Card.jsx
> +              {`${this.props.item.title}` && `${this.props.item.title}, `}
Суть данного кода: этот блок рендерится только при условии, если пропсом приходит title.

2020-12-05 19:01 UTC, ElenaDitiateva commented on client/src/tailwind.css
> +}
Подтянула - в main этого кода нет.

2020-12-06 14:37 UTC, ElenaDitiateva commented on client/src/components/Apartments/Cards.jsx
> +export default Cards;
Переделала

2020-12-06 14:38 UTC, ElenaDitiateva commented on client/src/components/ArtStudio/Card/Card.jsx
> +              {`${this.props.item.title}` && `${this.props.item.title}, `}
Сделала по-другому, добавила новый коммит

2020-12-07 19:30 UTC, Konfeta3-33 requested changes

2020-12-07 19:30 UTC, Konfeta3-33 commented on client/src/components/ArtStudio/Card/Card.jsx
> +
Лена, этот код надо упростить/убрать

2020-12-07 19:30 UTC, Konfeta3-33 commented on client/src/components/ArtStudio/Card/Card.jsx
> +              {displayTitle ? this.props.item.title + ',' : ''}
Лучше оставить title только там, где его необходимо отрендерить

2020-12-07 19:30 UTC, Konfeta3-33 commented on client/src/components/ArtStudio/Cards/Cards.jsx
> +          {cards.filter(item => [2,3,5].indexOf(item.id) !== -1).map((item) => (
и тут тогда не нужен будет фильтр

2020-12-07 19:30 UTC, Konfeta3-33 commented on client/src/components/ArtStudio/Cards/Items.js
> +    title: "",
а этот title убрать

2020-12-07 19:30 UTC, Konfeta3-33 commented on client/src/components/ArtStudio/Cards/Items.js
> +    title: "",
этот title тоже убрать

2020-12-07 19:30 UTC, Konfeta3-33 commented
Лена, небольшие комментарии

2020-12-13 11:39 UTC, Konfeta3-33 requested changes

2020-12-13 11:39 UTC, Konfeta3-33 commented on client/src/components/ArtStudio/Cards/Items.js
> +    page: "MainPage",
Это не нужное сво-во, его можно удалить. Давай вернем назад title.

2020-12-13 11:39 UTC, Konfeta3-33 commented on client/src/components/ArtStudio/Card/Card.jsx
>                <span className="block w-full">
span этот надо вынести из div

2020-12-13 11:39 UTC, Konfeta3-33 commented on client/src/components/ArtStudio/Card/Card.jsx
>              <div className="card__title text-gray-800 group-hover:text-yellow-700 text-left text-2xl">
а к этому div-у добавить условие {this.props.item.title && div...}

2020-12-13 11:39 UTC, Konfeta3-33 commented on client/src/components/ArtStudio/Card/Card.jsx
> +      title: this.props.title,
Это можно убрать из пропсов.

2020-12-13 11:39 UTC, Konfeta3-33 commented on client/src/components/ArtStudio/Cards/Cards.jsx
> +            item.page &&
Здесь тогда будет условие item.title &&

2020-12-13 11:39 UTC, Konfeta3-33 commented on client/src/components/ArtStudio/Cards/Cards.jsx
> +              title="ARTSTUDIO Nevsky, "
Этот пропс можно тоже убрать

2020-12-13 15:11 UTC, merged